### PR TITLE
Some pre-merge cleanups

### PR DESCRIPTION
**Pull request by greglandrum**
Wanted to run these past you first.
If you accept these here so that they end up on the PR against master, I'll go ahead and accept the PR against master.

### CODE REVIEW

**Comment by bp-kelley** [comment]
Was this ever merged?  I completely missed this.

@greglandrum

**Comment by greglandrum** [comment]
no, it wasn't

**Comment by greglandrum** [comment]
@bp-kelley Just making sure that you know that this merged onto your branch and not the trunk

**Comment by bp-kelley** [comment]
yep.  Wanted to test it first.  It looks innocuous.

I'll go ahead and do a PR in case you want to merge it.

**Pull request merged**
