### PR TITLE
thrown an exception at construction time

### PR DESCRIPTION
**Pull request by greglandrum**
This leaves your changes in place, just in case something odd happens later, and adds a test when the supplier is constructed to make sure that the stream can be read from.

### CODE REVIEW

**Comment by greglandrum** [comment]
hmm, on the Mac this doesn't work. grrrrr
exploring other options

**Comment by greglandrum** [comment]
theoretically fixed. let's see what the CI builds do
(and sorry for that crappy commit comment... it'll get squashed so I'm not going to bother fixing it).

This now also raises an exception if you attempt to construct a supplier from a completely empty file

**Review by bp-kelley — APPROVED** [review]
Looks like we should have had a line reader base class :)

**Comment by bp-kelley** [comment]
@greglandrum could you merge with master to get rid of the GETAWAY issue?

**Comment by greglandrum** [comment]
done

**Pull request merged**
